In [2]:
import torch
import torchvision
import numpy as np

print("Torch 버전:", torch.__version__)
print("Torchvision 버전:", torchvision.__version__)

Torch 버전: 1.11.0
Torchvision 버전: 0.12.0


In [4]:
data = [[1,2], [3,4]]
# 직접 텐서 만들기 (원본데이터와 메모리 공유 x)
x_data = torch.tensor(data)
print(x_data)

# numpy로 텐서 만들기 (원본데이터와 메모리 공유 o)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [6]:
# x데이터의 shape과 같은 torch 생성
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype = torch.float) # 0~1 사이의 랜덤값
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.2086, 0.4770],
        [0.4661, 0.7679]])


In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor, ones_tensor, zeros_tensor)

tensor([[0.2555, 0.2985, 0.9968],
        [0.1397, 0.9829, 0.0051]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# 6~10 사이의 랜덤값
min_val = 6
max_val = 10
rand_tensor = torch.rand(shape)* (max_val - min_val) +min_val
print(rand_tensor)

tensor([[9.1951, 7.0326, 6.4297],
        [7.5424, 6.7211, 7.8733]])


In [11]:
print(rand_tensor.shape)
print(rand_tensor.dtype)
print(rand_tensor.device)

torch.Size([2, 3])
torch.float32
cpu


In [12]:
# gpu가 있을때 탠서를 gpu에서 실행
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('device tensor is stored on: ', rand_tensor.device)

device tensor is stored on:  cpu


In [25]:
# 인덱싱과 슬라이싱
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = torch.cat([tensor, tensor], dim=0)
print(t1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
# 텐서의 요소별 곱하기
print(tensor.mul(tensor))
print(tensor*tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
# 텐서의 행렬곱 구하기
print(tensor.matmul(tensor))
print(tensor @ tensor)

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])
tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


In [26]:
# 텐서 더하기
print(tensor.add(4))
# add_()을 해주면 tensor값에 덧샘값이 저장됨

# 텐서와 numpy 배열은 메모리 공간을 공유하기 때문에 변경이 공유됨
t = torch.ones(5)
n = t.numpy()
print(t, n)

t.add_(1)
print(n)

tensor([[5., 4., 5., 5.],
        [5., 4., 5., 5.],
        [5., 4., 5., 5.],
        [5., 4., 5., 5.]])
tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]


# view - numpy의 reshape과 동일 , 원소의 수를 유지하며 텐서의 크기 변경'

In [36]:
t = np.array([[[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

print(ft.view([-1,3]))         # -1은 상관없이 알아서 줄이라는 뜻, 즉 (?,3)차원 행렬로 만들라는 의미
print(ft.view([-1,3]).shape)   # shape 안의 모든 값의 곲이 같아야함 2x2x3 = 4x3

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# squeeze - 크기가 1인 차원을 제거

In [38]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


# unsqueeze - 특정위치에 크기가 1인 차원을 추가

In [46]:
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)   # =print(ft.view([1,-1,1]).shape)
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)


torch.Size([3, 1])
tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])
torch.Size([1, 3, 1])
tensor([[[0.]],

        [[1.]],

        [[2.]]])
torch.Size([3, 1, 1])


torch.Size([3])
