In [16]:
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [27]:
class HeightWeightDataset(Dataset):
    def __init__(self, csv_path):
        self.data = []
        with open(csv_path, 'r', encoding='utf-8') as f:
            next(f)  # 첫번째 라인은 해더임으로 제외
            for line in f:
                _, height, weight = line.strip().split(',')
                height = float(height)
                weight = float(weight)
                convert2kg_data = round(self.convert2kg(weight),2)
                convert2cm_data = round(self.convert2cm(height),1)
                
                self.data.append([convert2cm_data, convert2kg_data])
            print(self.data)
        
    def __getitem__(self, index):
        data = torch.tensor(self.data[index], dtype=torch.float)
        return data
        
    def __len__(self):
        return len(self.data)
        
    def convert2kg(self, weight):
        return weight * 0.453592
    
    def convert2cm(self, height):
        return height * 2.54

In [28]:
dataset = HeightWeightDataset('./data/hw_200.csv')
dataLoader = DataLoader(dataset, 1, shuffle=True)

[[167.1, 51.25], [181.7, 61.91], [176.3, 69.41], [173.3, 64.56], [172.2, 65.45], [174.5, 55.93], [177.3, 64.18], [177.8, 61.9], [172.5, 50.97], [169.6, 54.73], [168.9, 57.81], [171.8, 51.77], [173.5, 56.98], [170.5, 55.55], [173.4, 52.66], [180.6, 63.5], [168.8, 58.74], [174.4, 64.85], [180.9, 62.55], [170.5, 56.26], [172.3, 64.08], [175.0, 65.11], [161.2, 44.41], [173.8, 58.74], [171.8, 64.34], [170.7, 58.84], [179.9, 64.6], [171.4, 59.67], [169.0, 49.14], [166.2, 51.66], [176.6, 46.86], [167.2, 54.77], [172.3, 57.06], [179.3, 61.79], [182.4, 63.55], [175.8, 58.4], [169.7, 64.32], [171.9, 54.99], [172.2, 59.58], [162.7, 48.4], [174.2, 56.41], [165.6, 56.64], [176.9, 63.35], [172.6, 62.31], [167.6, 48.28], [174.4, 58.4], [169.9, 66.08], [172.0, 52.99], [177.3, 65.14], [175.5, 61.2], [177.6, 66.69], [171.0, 57.3], [178.5, 56.92], [175.5, 52.49], [166.1, 56.01], [178.3, 67.08], [178.8, 70.71], [169.0, 58.09], [168.6, 54.15], [171.6, 60.7], [168.9, 58.39], [175.3, 62.39], [173.5, 58.86], 

In [32]:
for batch in dataLoader:
    print(batch,batch.shape)
    x = batch[:,0].unsqueeze(1)
    y = batch[:,1].unsqueeze(0)
    print(x,y)
    print(x.shape, y.shape)

tensor([[180.9000,  62.5500]]) torch.Size([1, 2])
tensor([[180.9000]]) tensor([[62.5500]])
torch.Size([1, 1]) torch.Size([1, 1])
tensor([[168.2000,  64.0300]]) torch.Size([1, 2])
tensor([[168.2000]]) tensor([[64.0300]])
torch.Size([1, 1]) torch.Size([1, 1])
tensor([[170.2000,  58.4300]]) torch.Size([1, 2])
tensor([[170.2000]]) tensor([[58.4300]])
torch.Size([1, 1]) torch.Size([1, 1])
tensor([[172.0000,  55.5700]]) torch.Size([1, 2])
tensor([[172.]]) tensor([[55.5700]])
torch.Size([1, 1]) torch.Size([1, 1])
tensor([[171.6000,  60.7000]]) torch.Size([1, 2])
tensor([[171.6000]]) tensor([[60.7000]])
torch.Size([1, 1]) torch.Size([1, 1])
tensor([[177.8000,  55.3600]]) torch.Size([1, 2])
tensor([[177.8000]]) tensor([[55.3600]])
torch.Size([1, 1]) torch.Size([1, 1])
tensor([[163.8000,  51.2100]]) torch.Size([1, 2])
tensor([[163.8000]]) tensor([[51.2100]])
torch.Size([1, 1]) torch.Size([1, 1])
tensor([[173.8000,  58.7400]]) torch.Size([1, 2])
tensor([[173.8000]]) tensor([[58.7400]])
torch.Size